# Generated by Django 4.0.4 on 2022-05-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urlShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longurl', models.URLField(max_length=300, unique=True)),
                ('shorturl', models.CharField(default=None, max_length=300, unique=True)),
            ],
        ),
    ]
